; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:vision-master-e290]
platform = espressif32
framework = arduino
board_upload.flash_size = 16MB
board_build.flash_size = 16MB
board_build.filesystem = littlefs
board_build.partitions = partitions/heltec_e290_16mb.csv

; Board choice: some people use heltec_wifi_lora_32_V3 as a base
; because Heltec E-Ink examples/documentation often assume it.
board = heltec_wifi_lora_32_V3

monitor_speed = 115200
board_upload.use_1200bps_touch = true

build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D Vision_Master_E290

lib_deps =
  todd-herbert/heltec-eink-modules
